# Generated by Django 5.2 on 2025-04-14 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_initial'),
        ('scheduling', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='conducted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Проведено преподавателем'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='schools.classroom', verbose_name='Аудитория'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='scheduling.schedule', verbose_name='Расписание'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('group', 'day_of_week', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('schedule', 'date')},
        ),
    ]
