# Generated by Django 5.2 on 2025-07-05 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_group_classroom_remove_group_end_date_and_more'),
        ('finance', '0002_alter_discount_currency_alter_expense_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('overdue', 'Просрочено'), ('paid', 'Оплачено')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_payments', to='courses.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Будущая оплата',
                'verbose_name_plural': 'Будущие оплаты',
                'ordering': ['payment_date'],
            },
        ),
    ]
