# Generated by Django 5.2 on 2025-06-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
