# Generated by Django 5.2 on 2025-04-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='available_branches',
            field=models.ManyToManyField(related_name='available_courses', to='schools.branch', verbose_name='Доступные филиалы'),
        ),
    ]
