# Generated by Django 4.2 on 2025-05-25 04:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_initial'),
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='schools.classroom', verbose_name='Аудитория'),
        ),
        migrations.AddField(
            model_name='group',
            name='lesson_days',
            field=models.CharField(choices=[('odd', 'Toq kunlar'), ('even', 'Juft kunlar'), ('weekend', 'Dam olish kunlar'), ('other', 'Boshqa')], default=django.utils.timezone.now, max_length=20, verbose_name='Дни занятий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='lesson_time',
            field=models.CharField(choices=[('06:00', '06:00'), ('06:30', '06:30'), ('07:00', '07:00'), ('07:30', '07:30'), ('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00')], default=1, max_length=5, verbose_name='Время занятий'),
            preserve_default=False,
        ),
    ]
