# Generated by Django 4.2 on 2025-06-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_group_classroom_group_lesson_days_group_lesson_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='lesson_time',
            field=models.CharField(choices=[('06:00', '06:00'), ('06:30', '06:30'), ('07:00', '07:00'), ('07:30', '07:30'), ('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00')], max_length=5, verbose_name='Время занятий'),
        ),
    ]
