# Generated by Django 4.2 on 2025-06-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_group_lesson_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='lesson_time',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Время занятий'),
        ),
    ]
