# Generated by Django 5.2 on 2025-06-26 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_group_lesson_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='group',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='group',
            name='lesson_days',
        ),
        migrations.RemoveField(
            model_name='group',
            name='lesson_time',
        ),
        migrations.RemoveField(
            model_name='group',
            name='start_date',
        ),
    ]
