# Generated by Django 4.2 on 2025-05-26 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='lesson',
        ),
    ]
