# Generated by Django 5.2 on 2025-06-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_remove_assignment_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('Checked', 'Checked')], default='draft', max_length=10, verbose_name='Status'),
        ),
    ]
