# Generated by Django 5.2 on 2025-05-02 06:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('courses', '0003_initial'),
        ('scheduling', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-lesson__date', '-lesson__start_time'], 'verbose_name': 'Посещаемость', 'verbose_name_plural': 'Посещаемость'},
        ),
        migrations.AlterModelOptions(
            name='attendancereport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отчет о посещаемости', 'verbose_name_plural': 'Отчеты о посещаемости'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='scheduling.lesson', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='marked_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время отметки'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Отметил'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Присутствует'), ('absent', 'Отсутствует'), ('late', 'Опоздал'), ('excused', 'Уважительная причина'), ('online', 'Онлайн')], default='absent', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_reports', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='end_date',
            field=models.DateField(verbose_name='Конец периода'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='courses.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='report_data',
            field=models.JSONField(help_text='JSON данные с результатами отчета', verbose_name='Данные отчета'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='start_date',
            field=models.DateField(verbose_name='Начало периода'),
        ),
    ]
