# Generated by Django 4.2 on 2025-05-23 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_initial'),
        ('attendance', '0002_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-lesson__date', '-lesson__start_time'], 'verbose_name': 'Attendance record', 'verbose_name_plural': 'Attendance records'},
        ),
        migrations.AlterModelOptions(
            name='attendancereport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Attendance report', 'verbose_name_plural': 'Attendance reports'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='scheduling.lesson', verbose_name='Lesson'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='marked_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Marked at'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Marked by'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused absence'), ('online', 'Attended online')], default='absent', max_length=10, verbose_name='Attendance status'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_reports', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='courses.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='report_data',
            field=models.JSONField(help_text='JSON data with report results', verbose_name='Report data'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
    ]
